[package]
name = "uppies"
version = "1.0.0"
edition = "2024"

[dependencies]
anyhow = "1.0.101"
dirs = "6"
clap = { version = "4.5.59", features = ["derive"] }
semver = "1.0.27"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
toml = "1.0.2"
